fighters = {
    1: ['mario'],
    2: ['donkeykong', 'dk', 'kong'],
    3: ['link'],
    4: ['samus'],
    5: ['darksamus', 'dsamus', 'd.samus'],
    6: ['yoshi'],
    7: ['kirby'],
    8: ['fox'],
    9: ['pikachu'],
    10: ['luigi'],
    11: ['ness'],
    12: ['captainfalcon', 'falcon', 'c.falcon', 'cfalcon', 'cf', 'capt.falcon', 'captfalcon'],
    13: ['jigglypuff', 'puff', 'jiggs'],
    14: ['peach'],
    15: ['daisy'],
    16: ['bowser'],
    17: ['iceclimbers', 'icies', 'ics'],
    18: ['sheik', 'shiek'],
    19: ['zelda'],
    20: ['doctormario', 'drmario', 'dr.mario', 'doc'],
    21: ['pichu'],
    22: ['falco'],
    23: ['marth'],
    24: ['lucina'],
    25: ['younglink', 'yink', 'ylink', 'y.link'],
    26: ['ganondorf', 'ganon', 'dorf'],
    27: ['mewtwo', 'mew2', 'm2'],
    28: ['roy'],
    29: ['chrom'],
    30: ['mr.game&watch', 'mr.gameandwatch', 'mr.gamenwatch', 'mrgame&watch', 'mrgameandwatch', 'mrgamenwatch',
         'game&watch', 'gameandwatch', 'gamenwatch', 'g&w', 'gnw'],
    31: ['metaknight', 'meta', 'mk'],
    32: ['pit'],
    33: ['darkpit', 'dpit', 'd.pit'],
    34: ['zerosuitsamus', 'zerosuit', 'zss'],
    35: ['wario'],
    36: ['snake'],
    37: ['ike'],
    38: ['pokemontrainer', 'pokemon', 'trainer', 'pt', 'pkmn', 'pkmntrainer'],
    39: ['diddykong', 'diddy'],
    40: ['lucas'],
    41: ['sonic'],
    42: ['kingdedede', 'dedede', '3d', 'd3', 'ddd', 'kingddd'],
    43: ['olimar', 'alph', 'pikmin'],
    44: ['lucario'],
    45: ['rob', 'r.o.b.', 'r.o.b'],
    46: ['toonlink', 'tink', 'tlink', 't.link'],
    47: ['wolf'],
    48: ['villager'],
    49: ['megaman', 'mega', 'mm'],
    50: ['wiifittrainer', 'wiifit', 'wft', 'wf'],
    51: ['rosalina', 'rosa'],
    52: ['littlemac', 'lilmac', 'mac', 'lil\'mac'],
    53: ['greninja', 'frog'],
    54: ['palutena', 'palu'],
    55: ['pac-man', 'pacman', 'pac'],
    56: ['robin'],
    57: ['shulk'],
    58: ['bowserjr', 'bowserjr.', 'bowserjunior', 'bj', 'bjr', 'bjr.', 'b.jr', 'b.jr.'],
    59: ['duckhunt', 'dh', 'dog'],
    60: ['ryu'],
    61: ['ken'],
    62: ['cloud'],
    63: ['corrin'],
    64: ['bayonetta', 'bayo'],
    65: ['inkling', 'ink'],
    66: ['ridley'],
    67: ['simon', 'simonbelmont', 'belmont'],
    68: ['richter', 'richterbelmont'],
    69: ['kingkrool', 'kingk.rool', 'krool', 'k.rool', 'rool', 'kingk', 'kingk.', 'kkr', 'rool', 'kkrool'],
    70: ['isabelle', 'belle'],
    71: ['incineroar', 'incin'],
    72: ['piranha plant', 'plant', 'piranha'],
    73: ['joker'],
    78: ['miibrawler', 'brawler'],
    79: ['miiswordfighter', 'swordfighter'],
    80: ['miigunner', 'gunner']
}

ids2fighters = {}
fighters2ids = {}
for i, fs in fighters.items():
    ids2fighters[i] = fs[0]
    for f in fs:
        fighters2ids[f] = i

fighter_icon_urls = {
    1: '',
    2: '',
    3: '',
    4: '',
    5: '',
    6: '',
    7: '',
    8: '',
    9: '',
    10: '',
    11: '',
    12: '',
    13: '',
    14: '',
    15: '',
    16: '',
    17: '',
    18: '',
    19: '',
    20: '',
    21: '',
    22: '',
    23: '',
    24: '',
    25: '',
    26: '',
    27: '',
    28: '',
    29: '',
    30: '',
    31: '',
    32: '',
    33: '',
    34: '',
    35: '',
    36: '',
    37: '',
    38: '',
    39: '',
    40: '',
    41: '',
    42: '',
    43: '',
    44: '',
    45: '',
    46: '',
    47: '',
    48: '',
    49: '',
    50: '',
    51: '',
    52: '',
    53: '',
    54: '',
    55: '',
    56: '',
    57: '',
    58: '',
    59: '',
    60: '',
    61: '',
    62: '',
    63: '',
    64: '',
    65: '',
    66: '',
    67: '',
    68: '',
    69: '',
    70: '',
    71: '',
    72: '',
    73: '',
    78: '',
    79: '',
    80: ''
}
