fighters = {
    1: ['mario'],
    2: ['donkey kong', 'donkeykong', 'dk', 'kong'],
    3: ['link'],
    4: ['samus'],
    5: ['dark samus', 'dsamus', 'darksamus'],
    6: ['yoshi'],
    7: ['kirby'],
    8: ['fox'],
    9: ['pikachu'],
    10: ['luigi'],
    11: ['ness'],
    12: ['captain falcon', 'captainfalcon', 'falcon', 'capt. falcon', 'capt falcon', 'c falcon', 'c. falcon',
         'c.falcon', 'cfalcon', 'cf', 'capt.falcon', 'captfalcon'],
    13: ['jigglypuff', 'puff'],
    14: ['peach'],
    15: ['daisy'],
    16: ['bowser'],
    17: ['ice climbers', 'iceclimbers', 'icies', 'ics'],
    18: ['sheik', 'shiek'],
    19: ['zelda'],
    20: ['doctor mario', 'dr mario', 'dr. mario', 'doctormario', 'drmario', 'dr.mario', 'doc'],
    21: ['pichu'],
    22: ['falco'],
    23: ['marth'],
    24: ['lucina'],
    25: ['young link', 'younglink', 'yink', 'ylink'],
    26: ['ganondorf', 'ganon', 'dorf'],
    27: ['mewtwo', 'mew2', 'm2'],
    28: ['roy'],
    29: ['chrom'],
    30: ['game & watch', 'game and watch', 'g & w', 'game n watch', 'game&watch', 'gameandwatch', 'g&w', 'gnw',
         'mr game & watch', 'mr game and watch', 'mr game n watch', 'mr. game & watch', 'mr. game and watch',
         'mr. game n watch'],
    31: ['meta knight', 'metaknight', 'meta', 'mk'],
    32: ['pit'],
    33: ['dark pit', 'darkpit', 'dpit'],
    34: ['zero suit samus', 'zero suit', 'zerosuitsamus', 'zerosuit', 'zss'],
    35: ['wario'],
    36: ['snake'],
    37: ['ike'],
    38: ['pokemon trainer', 'pokemontrainer', 'pokemon', 'trainer', 'pt', 'pkmn', 'pkmn trainer', 'pkmntrainer'],
    39: ['diddy kong', 'diddykong', 'diddy'],
    40: ['lucas'],
    41: ['sonic'],
    42: ['king dedede', 'kingdedede', 'dedede', '3d', 'd3', 'ddd'],
    43: ['olimar', 'alph', 'pikmin'],
    44: ['lucario'],
    45: ['rob', 'r.o.b.', 'r.o.b', 'r. o. b.', 'r. o. b'],
    46: ['toon link', 'toonlink', 'tink', 'tlink'],
    47: ['wolf'],
    48: ['villager'],
    49: ['megaman', 'mega man', 'mega', 'mm'],
    50: ['wii fit trainer', 'wii fit', 'wiifittrainer', 'wiifit', 'wft', 'wf'],
    51: ['rosalina', 'rosa'],
    52: ['little mac', 'lil mac', 'littlemac', 'lilmac', 'mac'],
    53: ['greninja', 'frog'],
    54: ['mii brawler', 'mii', 'brawler'],
    55: ['palutena', 'palu'],
    56: ['pac-man', 'pacman', 'pac man', 'pac'],
    57: ['robin'],
    58: ['shulk'],
    59: ['bowser jr', 'bowser jr.', 'bowser junior', 'bowserjr', 'bowserjr.', 'bowserjunior', 'bj', 'bjr'],
    60: ['duck hunt', 'duckhunt', 'dh'],
    61: ['ryu'],
    62: ['cloud'],
    63: ['corrin'],
    64: ['bayonetta', 'bayo'],
    65: ['inkling', 'ink'],
    66: ['ridley'],
    67: ['simon', 'simon belmont', 'simonbelmont', 'belmont'],
    68: ['richter', 'richter belmont', 'richterbelmont'],
    69: ['king k rool', 'king k. rool', 'kingkrool', 'kingk.rool', 'k rool', 'k. rool', 'krool', 'k.rool', 'rool',
         'king k', 'king k.', 'kingk', 'king k.', 'kkr', 'rool'],
    70: ['piranha plant', 'piranha plant', 'plant'],
    71: ['ken'],
    72: ['isabelle', 'belle'],
    73: ['incineroar'],
    74: ['mii swordfighter', 'miiswordfighter', 'swordfighter', 'mii sword fighter', 'sword fighter'],
    75: ['mii gunner', 'mii gunner', 'gunner']
}

fighters_to_ids = {}
for i, fs in fighters.items():
    for f in fs:
        fighters_to_ids[f] = i
